---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets

- resources:
    cpu: true
    memory: true
    disk: /
    uptime: true
    cputemp: true

- datetime:
    text_size: xl
    locale: sk
    format:
      dateStyle: long
      timeStyle: long
      hourCycle: h23


# - logo:
    # icon: /images/kpi-logo.svg

- greeting:
    text_size: 4xl
    text: "${IOTGW_DEPARTMENT}/${IOTGW_ROOM} IoT Gateway"

