Mqtt:
  address: "${MOSQUITTO_HOST}"
  port: "${MOSQUITTO_PORT}"
  username: "${MOSQUITTO_USERNAME}"
  password: "${MOSQUITTO_PASSWORD}"

Influxdb:
  url: "${INFLUXDB_URL}"
  token: "${INFLUXDB_TOKEN}"
  org: "${INFLUXDB_ORG}"

Validators:
  - topics: ["kpi/+/temperature/#"]
    bucket: "Measurements"
    tagsPattern: "department/room"
    measurement: "temperature"
    schema: "./config/schemas/temperature-value.json"
    transform:
      timestamp: "dt"
      fields:
        - name: "temperature"
          path: "temperature"
      tags:
        - name: "battery"
          path: "battery"

  - topics: ["kpi/+/humidity/#"]
    bucket: "Measurements"
    tagsPattern: "department/room"
    measurement: "humidity"
    schema: "./config/schemas/humidity-value.json"
    transform:
      timestamp: "dt"
      fields:
        - name: "humidity"
          path: "humidity"
      tags:
        - name: "battery"
          path: "battery"

  - topics: ["test/+/door/#"]
    bucket: "Measurements"
    measurement: "door"
    tagsPattern: "department/room"
    schema: "./config/schemas/door-value.json"
    transform:
      timestamp: "dt"
      fields:
        - name: "status"
          path: "status"
      tags:
        - name: "battery"
          path: "battery"
