---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets

- resources:
    cpu: true
    memory: true
    disk: /
    uptime: true
    cputemp: true 

- datetime:
    text_size: xl
    locale: sk
    format:
      dateStyle: long
      timeStyle: long 
      hourCycle: h23


- logo:
    icon: https://magazin.kpi.fei.tuke.sk/images/kpi-logo.svg

