version: "2.4"

services:
  provisioning:
    build:
      context: provisioning
    restart: no
    # env_file:
    #   - .env
    volumes:
      - zigbee2mqtt_data:/mnt/zigbee2mqtt/
      - mosquitto_config:/mnt/mosquitto/
      - homepage_config:/mnt/homepage/config/
      - homepage_images:/mnt/homepage/images/
      - theengs_config:/mnt/theengs/
      - nodered_data:/mnt/nodered/
      - telegraf_config:/mnt/telegraf/
    labels:
      io.resin.features.balena-socket: "1"
      io.balena.features.dbus: "1"

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    volumes:
      - homepage_config:/app/config
      - homepage_images:/app/public/images
    # - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    ports:
      - 80:3000
    depends_on:
      - provisioning
    labels:
      io.balena.features.balena-socket: "1"

  mosquitto:
    image: eclipse-mosquitto:2.0
    restart: always
    volumes:
      - mosquitto_config:/mosquitto/config:ro
    depends_on:
      - provisioning
    ports:
      - 1883:1883

  telegraf:
    image: telegraf:1.31-alpine
    restart: always
    depends_on:
      - provisioning
      - mosquitto
    user: telegraf:991
    volumes:
      - telegraf_config:/etc/telegraf:ro
    #       - /:/hostfs:ro
    #       - HOST_ETC=/hostfs/etc
    #       - HOST_PROC=/hostfs/proc
    #       - HOST_SYS=/hostfs/sys
    #       - HOST_VAR=/hostfs/var
    #       - HOST_RUN=/hostfs/run
    #       - HOST_MOUNT_PREFIX=/hostfs
    labels:
      io.resin.features.balena-socket: "1"


  theengs:
    image: theengs/gateway:latest
    restart: always
    depends_on:
      - provisioning
      - mosquitto
    volumes:
      - theengs_config:/root/
    environment:
      UDEV: 1
      DBUS_SYSTEM_BUS_ADDRESS: unix:path=/host/run/dbus/system_bus_socket
    labels:
      io.balena.features.dbus: "1"
    working_dir: /opt/venv
    command: /bin/bash -ec "source bin/activate && python3 -m TheengsGateway"


  chrony:
    image: cturra/ntp:latest
    restart: always
    ports:
      - 123:123/udp
    # environment:
    #   LOG_LEVEL: 0


  nodered:
    image: nodered/node-red:4.0.0-minimal
    restart: always
    ports:
      - 1880:1880
    volumes:
      - nodered_data:/data
    depends_on:
      - provisioning
      - mosquitto
    # labels:
    #   io.balena.features.supervisor-api: 1
    entrypoint: /data/entrypoint.sh

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:1.38.0
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - provisioning
      - mosquitto
    privileged: true
    volumes:
      - zigbee2mqtt_data:/app/data/
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: unix:path=/host/run/dbus/system_bus_socket
    labels:
      io.balena.features.dbus: "1"

  wifi-repeater:
      build: wifi-repeater
      privileged: true
      depends_on:
      - provisioning
      labels:
        io.balena.features.dbus: "1"

volumes:
  nodered_data:
  zigbee2mqtt_data:
  mosquitto_config:
  homepage_config:
  homepage_images:
  theengs_config:
  telegraf_config:
