version: "3"

services:

  nodered:
    image: nodered/node-red
    restart: always
    ports:
    - 1880:1880
    volumes:
    - nodered_data:/data
    labels:
      homepage.group: Services
      homepage.name: Node-RED
      homepage.icon: nodered.png
      homepage.href: http://${HOSTIP:-localhost}:1880
      homepage.description: Node-RED

  zigbee2mqtt:
    restart: always
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8000:8080
    environment:
      - TZ=Europe/Bratislava
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/ttyUSB0:/dev/ttyUSB0
    labels:
      homepage.group: Services
      homepage.name: Zigbee2MQTT
      homepage.icon: zigbee2mqtt.png
      homepage.href: http://${HOSTIP:-localhost}:8000
      homepage.description: Zigbee to MQTT bridge
    networks:
      - iotgw

volumes:
  nodered_data:

networks:
  iotgw:
    external: true
