homeassistant: false
permit_join: true
mqtt:
  base_topic: gateway/zigbee
  server: mqtt://mosquitto
  user: maker
  password: maker-caprica-password
  client_id: zigbee2mqtt
frontend: true
serial:
  adapter: ezsp
devices:
  '0xb43522fffebf2050':
    friendly_name: switch
  '0xa4c138b5fd53b168':
    friendly_name: door
  '0xa4c13814d8997802':
    friendly_name: pir 1
  '0xa4c13865412e4211':
    friendly_name: pir 2
  '0xdc8e95fffe76bc26':
    friendly_name: knob
  '0x70ac08fffea6682a':
    friendly_name: ir controller
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
