homeassistant: false
permit_join: false
mqtt:
  base_topic: gateway/zigbee
  server: mqtt://{{ MQTT_BROKER }}
  user: {{ MQTT_USER }}
  password: {{ MQTT_PASSWORD }}
  client_id: zigbee2mqtt
frontend: true
serial:
  adapter: ezsp
  port: {{ ZIGBEE_ADAPTER }}
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
