# Home Assistant integration (MQTT discovery)
homeassistant: false

# allow new devices to join
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: gateway/zigbee
  # MQTT server URL
  server: mqtt://mosquitto
  # MQTT server authentication, uncomment if required:
  # user: my_user
  # password: my_password

# enable UI
frontend: true

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  port: /dev/ttyACM0

